# Generated by Django 5.0.6 on 2024-06-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(max_length=500, upload_to='blog_thumbnail_directory'),
        ),
    ]
